name: Setup
description: Set up project environment and test environment.
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org
        cache: yarn
