name: Pull Request Test

on:
  pull_request:
    branches: [main, release/*]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: |
          yarn
          yarn build:module
      - run: yarn run test

  # TODO: Apply when you're done setting up your storybook environment
  # storybook-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/setup
  #     - run: run test:storybook
